<?php
/**
 * @copyright Copyright (c) Sigma Ukraine
 * @package   Yiitrn
 */

/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
	' Hint: You may login with {login}' => ' Подсказка: Вы можете войти с помощью {login}',
	'Admin page' => 'Страница администратора',
	'Error' => 'Ошибка',
	'Fields with {asterix} are required.' => 'Поля, отмеченные {asterix} обязательны к заполнению.',
	'First' => 'В начало',
	'Go to Page' => 'К странице',
	'Home' => 'Главная',
	'Index' => 'Стартовая',
	'Last' => 'В конец',
	'Login' => 'Войти',
	'Logout' => 'Выйти',
	'Next' => 'Следующая',
	'Pages' => 'Страницы',
	'Password Recovery' => 'Восстановление пароля',
	'Please fill out the following form with your login credentials' => 'Пожалуйста, заполните следующую форму вашими креденшиалами',
	'Previous' => 'Предыдущая',
	'Profile' => 'Профиль',
	'Register' => 'Регистрация',
	'Generate Code' => 'Обновить код',
	'Registration' => 'Регистрация',
	'User Profile' => 'Профиль пользователя',
	'Edit profile' => 'Редактировать профиль',
	'Save' => 'Сохранить',
	'Cancel' => 'Отмена',
	'Change password' => 'Изменить пароль',
	'Author' => 'Автор',
	'Comment' => 'Комментарий',
	'Comments' => 'Комментарии',
	'Leave a Comment' => 'Оставьте комментарий',
	'Page' => 'Страница',
	'Reply' => 'Ответить',
	'You are not allowed to leave comments' => 'Вы не можете оставлять комментарии',
	'Send' => 'Отправить',
	'Continue' => 'Читать дальше',
	'Recent comments' => 'Последние комментарии',
	'Published on' => 'Опубликовано',
	'Recent pages' => 'Последние страницы',
	'This page is not visible' => 'Эта страница недоступна',
	'Do you already have an account on one of these sites? Click the logo to log in with it here:' => 'У Вас уже есть аккаунт на этих сайтах? Нажмите на лого, чтобы зайти через него:'
);
